### PR TITLE
Apply fix of @whoutman

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
see https://github.com/tue-ropod/ropod-project-software/commit/a9472e9e7d7e47871d5a14e8f1436d31f7865bfd

### CODE REVIEW

**Comment by rokusottervanger** [comment]
Too bad this couldn't be a pull request from @whoutman himself because the ropod project didn't fork our repo. But the fix looks good to me.

**Comment by rokusottervanger** [comment]
BTW, the issue is not described anywhere. It just so happens that I knew what the issue was. Please describe the problem in an issue and refer to the issue when making a pull request, or at least describe the issue in the pr.

**Review by rokusottervanger — APPROVED** [review]

**Comment by MatthijsBurgh** [comment]
@whoutman did create an issue, I didn't mention it. Sorry.

**Comment by MatthijsBurgh** [comment]
Fixes #15

**Comment by rokusottervanger** [comment]
Nice! Missed that one ;)

**Pull request merged**
